version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app]
    tty: true
    command: npm start
    environment:
       DATABASE_URL: mongodb://root:root@db:27017/nest?authSource=admin
       GOOGLE_MAPS_API_KEY: AIzaSyADF3c9ug7CHwvS4GSBAVWCVgbjqTQoO_c
      
  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest

volumes:
  mongodb_data:
    driver: local